apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2020-06-21T11:17:07Z"
  generation: 1
  labels:
    app: hasher
  name: hasher
  namespace: default
  resourceVersion: "19325"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/hasher
  uid: 2bcb6796-c5b3-4520-9c95-81ff0af1c3d2
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: hasher
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hasher
    spec:
      containers:
      - image: dockercoins/hasher:v0.1
        imagePullPolicy: IfNotPresent
        name: hasher
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-06-21T11:17:51Z"
    lastUpdateTime: "2020-06-21T11:17:51Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-06-21T11:17:07Z"
    lastUpdateTime: "2020-06-21T11:17:51Z"
    message: ReplicaSet "hasher-7b98b6966d" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
