apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-06-21T11:46:57Z"
  labels:
    app: hasher
  name: hasher
  namespace: default
  resourceVersion: "2101"
  selfLink: /api/v1/namespaces/default/services/hasher
  uid: 22da0470-ac78-4c19-a89c-2f7b169fe857
spec:
  clusterIP: 10.97.23.70
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: hasher
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
