apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-06-21T11:46:56Z"
  labels:
    app: redis
  name: redis
  namespace: default
  resourceVersion: "2093"
  selfLink: /api/v1/namespaces/default/services/redis
  uid: c40816c7-122b-427b-9128-9ac8c7642f37
spec:
  clusterIP: 10.102.205.216
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
