apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-06-21T11:17:40Z"
  labels:
    app: rng
  name: rng
  namespace: default
  resourceVersion: "19287"
  selfLink: /api/v1/namespaces/default/services/rng
  uid: 6d2990d3-8320-46ab-9d0e-150d98d99b9d
spec:
  clusterIP: 10.104.63.71
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: rng
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
