apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2020-06-21T11:46:34Z"
  generation: 1
  labels:
    app: worker
  name: worker
  namespace: default
  resourceVersion: "2059"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/worker
  uid: aa06fdfd-d7d5-4cac-934c-2d3f8eb25136
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: worker
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: worker
    spec:
      containers:
      - image: dockercoins/worker:v0.1
        imagePullPolicy: IfNotPresent
        name: worker
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-06-21T11:46:35Z"
    lastUpdateTime: "2020-06-21T11:46:35Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-06-21T11:46:34Z"
    lastUpdateTime: "2020-06-21T11:46:35Z"
    message: ReplicaSet "worker-745744775c" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
