apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: frontend
  namespace: default
spec:
  template:
    spec:
      containers:
              - image: docker.io/wattana8001/frontend:v1

