apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2020-06-21T15:05:49Z"
  generation: 1
  labels:
    app: adder
  name: adder
  namespace: default
  resourceVersion: "2116"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/adder
  uid: 457300e5-977c-4cf5-87b8-4e1e827dfd1b
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: adder
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: adder
    spec:
      containers:
      - image: chanwit/adder
        imagePullPolicy: Always
        name: adder
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-06-21T15:06:00Z"
    lastUpdateTime: "2020-06-21T15:06:00Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-06-21T15:05:49Z"
    lastUpdateTime: "2020-06-21T15:06:00Z"
    message: ReplicaSet "adder-669b6cb68" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
