apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-06-21T15:06:21Z"
  labels:
    app: source
  name: source
  namespace: default
  resourceVersion: "2183"
  selfLink: /api/v1/namespaces/default/services/source
  uid: 58f67de3-c0f0-4049-962d-629f5fdf76c4
spec:
  clusterIP: 10.109.105.10
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: source
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
