apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-06-21T15:06:21Z"
  labels:
    app: suber
  name: suber
  namespace: default
  resourceVersion: "2190"
  selfLink: /api/v1/namespaces/default/services/suber
  uid: d3a15c10-c012-499c-b7f1-e040717ed59d
spec:
  clusterIP: 10.111.35.40
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: suber
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
